DROP TABLE IF EXISTS Member;

CREATE TABLE Member
(
    id  IDENTITY    PRIMARY KEY,
    user_id VARCHAR(30) NOT NULL UNIQUE,
    user_pw VARCHAR(300) NOT NULL,
    create_date DATE DEFAULT CURRENT_TIMESTAMP,
    update_date DATE DEFAULT CURRENT_TIMESTAMP
)